// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcaYUmK6gqS5_ihOADl0YnkZoVCqayf9w',
    appId: '1:87608193244:web:d1ca9177c9953bf06a4419',
    messagingSenderId: '87608193244',
    projectId: 'glicoeduca',
    authDomain: 'glicoeduca.firebaseapp.com',
    storageBucket: 'glicoeduca.firebasestorage.app',
    measurementId: 'G-Z5Z77DRRQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgePQnWR8BZ13V633Rm44F7DzzHAHh24Y',
    appId: '1:87608193244:android:9eb59b84c422b6df6a4419',
    messagingSenderId: '87608193244',
    projectId: 'glicoeduca',
    storageBucket: 'glicoeduca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHliqqbBhJ0e8Ijr8j_vXrzAypdlXXlY',
    appId: '1:87608193244:ios:188fd9eaae48e2056a4419',
    messagingSenderId: '87608193244',
    projectId: 'glicoeduca',
    storageBucket: 'glicoeduca.firebasestorage.app',
    iosBundleId: 'com.example.glicoeduca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtHliqqbBhJ0e8Ijr8j_vXrzAypdlXXlY',
    appId: '1:87608193244:ios:188fd9eaae48e2056a4419',
    messagingSenderId: '87608193244',
    projectId: 'glicoeduca',
    storageBucket: 'glicoeduca.firebasestorage.app',
    iosBundleId: 'com.example.glicoeduca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcaYUmK6gqS5_ihOADl0YnkZoVCqayf9w',
    appId: '1:87608193244:web:833297a59358eac06a4419',
    messagingSenderId: '87608193244',
    projectId: 'glicoeduca',
    authDomain: 'glicoeduca.firebaseapp.com',
    storageBucket: 'glicoeduca.firebasestorage.app',
    measurementId: 'G-TYQC9FREFX',
  );
}
